### PR TITLE
Update aspnetcore-2.0.md

### PR DESCRIPTION
**Pull request by rogeriorrodrigues**
Alter Title link . Line 31

### CODE REVIEW

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C27%5C56af13d6-f547-9b69-c086-33888bd3a4cd%5CPullRequest%5C201710270159509643-11%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=K262SGn2LsbnHTxUqIn5HK11HDkBBLRIaJIqBRIL3lM%3D&st=2017-10-27T01%3A54%3A54Z&se=2017-11-27T01%3A59%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rogeriorrodrigues** [comment]
Alter link title in line 31

**Comment by v-radelg** [comment]
Hi @rogeriorrodrigues , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@rogeriorrodrigues , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Pull request merged**
