### PR TITLE
Update Creating Backend Services for Native M. App

### PR DESCRIPTION
**Pull request by sjcostaneto**

### CODE REVIEW

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C25%5C56af13d6-f547-9b69-c086-33888bd3a4cd%5CPullRequest%5C201710251946364422-6%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=cdGVfMrp281z1LXzqxk3TRqcghU%2BMBVtWqXvkCRjEmE%3D&st=2017-10-25T19%3A41%3A54Z&se=2017-11-25T19%3A46%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
Hi @sjcostaneto , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by sjcostaneto** [comment]
[erro] Cannot sync git repo because branch live has been deleted.
What branch do I have to modify?
I wanted this help not to make that mistake anymore.

**Comment by gosali** [comment]
@sjcostaneto , Thank you for your feedback and suggestion! 
  
The suggestion will be merged to the production, we will re-release this articles in the next loc release round. 
We will check the branch issue. And restore the live branch if needed.
  
Microsoft C&E Localization Team

**Pull request merged**
