### PR TITLE
Updated inforcing-SSL translation.

### PR DESCRIPTION
**Pull request by isadorasophia**
Improved Portuguese translation of the document.

### CODE REVIEW

**Comment by v-tisip** [comment]
### :white_check_mark: Validation status: partially passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/tutorials/razor-pages-vsc/model.md](https://github.com/isadorasophia/Docs.pt-br/blob/patch-2/aspnetcore/tutorials/razor-pages-vsc/model.md) | :x:Error | [View](https://review.docs.microsoft.com/pt-br/aspnet/core/tutorials/razor-pages-vsc/model?branch=pr-pt-br-5) | [Details](#user-content-aspnetcore%2Ftutorials%2Frazor-pages-vsc%2Fmodel.md)
[aspnetcore/publishing/visual-studio-tools-for-docker.md](https://github.com/isadorasophia/Docs.pt-br/blob/patch-2/aspnetcore/publishing/visual-studio-tools-for-docker.md) | :warning:Warning | [View](https://review.docs.microsoft.com/pt-br/aspnet/core/publishing/visual-studio-tools-for-docker?branch=pr-pt-br-5) | [Details](#user-content-aspnetcore%2Fpublishing%2Fvisual-studio-tools-for-docker.md)
[aspnetcore/security/enforcing-ssl.md](https://github.com/isadorasophia/Docs.pt-br/blob/patch-2/aspnetcore/security/enforcing-ssl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/pt-br/aspnet/core/security/enforcing-ssl?branch=pr-pt-br-5) |

<a name="aspnetcore%2Ftutorials%2Frazor-pages-vsc%2Fmodel.md"></a>
### [aspnetcore/tutorials/razor-pages-vsc/model.md](https://github.com/isadorasophia/Docs.pt-br/blob/patch-2/aspnetcore/tutorials/razor-pages-vsc/model.md)
 - **Line 12**: **[Error]** Start line 19 exceeds total lines 15 when resolving &quot;[!code-csharp[Main](../../tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Models/MovieContext.cs?range=1-12,14-17,19-21)]&quot;

<a name="aspnetcore%2Fpublishing%2Fvisual-studio-tools-for-docker.md"></a>
### [aspnetcore/publishing/visual-studio-tools-for-docker.md](https://github.com/isadorasophia/Docs.pt-br/blob/patch-2/aspnetcore/publishing/visual-studio-tools-for-docker.md)
 - **Line 39**: **[Warning]** Invalid file link:(~/publishing/visual-studio-tools-for-docker/_static/settings-shared-drives-win.png).
 - **Line 47**: **[Warning]** Invalid file link:(~/publishing/visual-studio-tools-for-docker/_static/project-add-docker-support.png).
 - **Line 51**: **[Warning]** Invalid file link:(~/publishing/visual-studio-tools-for-docker/_static/right-click-add-docker-support.png).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C25%5C56af13d6-f547-9b69-c086-33888bd3a4cd%5CPullRequest%5C201710251550038667-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=RneQCKZirqU%2F8ykXNchtMmswo2Eg3Wmjp3HsWLF2nzw%3D&st=2017-10-25T15%3A48%3A06Z&se=2017-11-25T15%3A53%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
Hi @isadorasophia , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@isadorasophia , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Comment by v-tisip** [comment]
### :white_check_mark: Validation status: partially passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/tutorials/razor-pages/model.md](https://github.com/isadorasophia/Docs.pt-br/blob/patch-2/aspnetcore/tutorials/razor-pages/model.md) | :x:Error | [View](https://review.docs.microsoft.com/pt-br/aspnet/core/tutorials/razor-pages/model?branch=pr-pt-br-5) | [Details](#user-content-aspnetcore%2Ftutorials%2Frazor-pages%2Fmodel.md)
[aspnetcore/publishing/visual-studio-tools-for-docker.md](https://github.com/isadorasophia/Docs.pt-br/blob/patch-2/aspnetcore/publishing/visual-studio-tools-for-docker.md) | :warning:Warning | [View](https://review.docs.microsoft.com/pt-br/aspnet/core/publishing/visual-studio-tools-for-docker?branch=pr-pt-br-5) | [Details](#user-content-aspnetcore%2Fpublishing%2Fvisual-studio-tools-for-docker.md)
[aspnetcore/security/enforcing-ssl.md](https://github.com/isadorasophia/Docs.pt-br/blob/patch-2/aspnetcore/security/enforcing-ssl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/pt-br/aspnet/core/security/enforcing-ssl?branch=pr-pt-br-5) |

<a name="aspnetcore%2Ftutorials%2Frazor-pages%2Fmodel.md"></a>
### [aspnetcore/tutorials/razor-pages/model.md](https://github.com/isadorasophia/Docs.pt-br/blob/patch-2/aspnetcore/tutorials/razor-pages/model.md)
 - **Line 12**: **[Error]** Start line 19 exceeds total lines 15 when resolving &quot;[!code-csharp[Main](../../tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Models/MovieContext.cs?range=1-12,14-17,19-21)]&quot;
 - **Line 58**: **[Warning]** Invalid file link:(~/tutorials/first-mvc-app/adding-model/_static/pmc.png).

<a name="aspnetcore%2Fpublishing%2Fvisual-studio-tools-for-docker.md"></a>
### [aspnetcore/publishing/visual-studio-tools-for-docker.md](https://github.com/isadorasophia/Docs.pt-br/blob/patch-2/aspnetcore/publishing/visual-studio-tools-for-docker.md)
 - **Line 39**: **[Warning]** Invalid file link:(~/publishing/visual-studio-tools-for-docker/_static/settings-shared-drives-win.png).
 - **Line 47**: **[Warning]** Invalid file link:(~/publishing/visual-studio-tools-for-docker/_static/project-add-docker-support.png).
 - **Line 51**: **[Warning]** Invalid file link:(~/publishing/visual-studio-tools-for-docker/_static/right-click-add-docker-support.png).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C1%5C56af13d6-f547-9b69-c086-33888bd3a4cd%5CPullRequest%5C201711012210581982-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MTV3L4bkgun%2FxLWOLN38Wpr0At%2BJoAK2W0zwLMruqJg%3D&st=2017-11-01T22%3A10%3A03Z&se=2017-12-02T22%3A15%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
