### PR TITLE
Update native-mobile-backend.md

### PR DESCRIPTION
**Pull request by rogeriorrodrigues**
Update language expressions and translate pt-br

### CODE REVIEW

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C30%5C56af13d6-f547-9b69-c086-33888bd3a4cd%5CPullRequest%5C201710302046174619-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oinIYa3JdC1vxWqndRs%2FZjizdhC7mhUN3ZL4A02jg5I%3D&st=2017-10-30T20%3A41%3A30Z&se=2017-11-30T20%3A46%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sjcostaneto** [comment]
Tenta colocar no ramo master que não vai dar esse erro. Não sei o motivo, mas funciona. Entrei em contato para saber em que ramo publicamos, mas não tive resposta ainda.

**Comment by gosali** [comment]
@sjcostaneto, Please submit all PRs in the 'Live' branch.

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C1%5C56af13d6-f547-9b69-c086-33888bd3a4cd%5CPullRequest%5C201711012230065338-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nMam5bal4V1kz7A%2BjRdM2siFMEzZG0yOHEWGyfl8Hx8%3D&st=2017-11-01T22%3A25%3A10Z&se=2017-12-02T22%3A30%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C1%5C56af13d6-f547-9b69-c086-33888bd3a4cd%5CPullRequest%5C201711012233580750-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kufqdiPojCrmpIPigepC4i33AanhWmviFcfTx3A2epE%3D&st=2017-11-01T22%3A29%3A02Z&se=2017-12-02T22%3A34%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C1%5C56af13d6-f547-9b69-c086-33888bd3a4cd%5CPullRequest%5C201711012235525765-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=yH2VPnGZ3DVN4%2ByK6P0aL5f6mgGe%2FkKwPXqnXa7Dvm8%3D&st=2017-11-01T22%3A31%3A00Z&se=2017-12-02T22%3A36%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by gosali** [comment]
@rogeriorrodrigues, Thank you for your feedback and suggestion! 
  
The suggestion will be merged to the production, we will re-release this articles in the next loc release round. 
  
Microsoft C&E Localization Team

**Pull request merged**
