### PR TITLE
Update identity-enable-qrcodes

### PR DESCRIPTION
**Pull request by sjcostaneto**
Update identity-enable-qrcodes

### CODE REVIEW

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 356**: **[Error]** Error happened in build.entrypoint.ps1. Please build your target branch first and then reopen this pull request to do another round of verification. If the issue still happens, open a ticket in http://SiteHelp and include the following error message for our team to troubleshoot: The process cannot access the file &#39;tmp_pack_ddxP18&#39; because it is being used by another process.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C27%5C56af13d6-f547-9b69-c086-33888bd3a4cd%5CPullRequest%5C201710270529099982-17%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2FGon2hOUt6TxZvmb%2Fy83olxNuR1l2mr4rju5DsqUPek%3D&st=2017-10-27T05%3A37%3A14Z&se=2017-11-27T05%3A42%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dnfgituser** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 356**: **[Error]** Error happened in build.entrypoint.ps1. Please build your target branch first and then reopen this pull request to do another round of verification. If the issue still happens, open a ticket in http://SiteHelp and include the following error message for our team to troubleshoot: The process cannot access the file &#39;tmp_pack_hDKfjc&#39; because it is being used by another process.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C27%5C56af13d6-f547-9b69-c086-33888bd3a4cd%5CPullRequest%5C201710272034539096-17%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QYCJ3oFaZNYUoO3rmXdLa0qZBE2N3IMJaqwQWt9Qd8U%3D&st=2017-10-27T20%3A41%3A56Z&se=2017-11-27T20%3A46%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by gosali** [comment]
Hi @sjcostaneto , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Pull request merged**
